### ISSUE TITLE
any way to extract/print the Fock matrix from GFN-xTB ? 

### ISSUE THREAD

**Issue by linminhtoo** [tblite/tblite#101]
Hello,

first of all thank you for your awesome work! my main use of `tblite` has been to extract the intermediate matrices, like the overlap matrix, the hamiltonian matrix and so on, which was not so trivial with `xTB`. I've tried it on a few examples and everything has worked wonderfully well. 

however, I am also in need of the Fock matrix `F` for the machine learning model that I want to build. Is there any way I can also extract the last iteration's fock matrix somehow? I was thinking it shouldn't be too complicated given that we already extract the other matrices as part of the self-iterative procedure. and surely `F` must have been calculated to obtain the solution, which is the energy.

 Please pardon if my question is very simple as I have basically 0 knowledge of Fortran, and only rudimentary understanding of quantum physics.

Thank you very much!

Best,
Min Htoo

**Comment by awvwgk** [comment]
Is it sufficient to reconstruct the full Hamiltonian from the orbital energies and coefficients?

**Comment by linminhtoo** [comment]
> Is it sufficient to reconstruct the full Hamiltonian from the orbital energies and coefficients?

Sorry, could you please give me pointers on how exactly I can do this? I understand that orbital energies and orbital coefficients are both in the result dictionary. Thank you very much for your help.

**Comment by linminhtoo** [comment]
For context, the paper I am trying to reproduce explicitly requires 4 matrices as inputs, the Fock matrix F, the density matrix D (already in result dict), the overlap matrix S (already in result dict) and the core Hamiltonian H (already in result dict).

**Comment by awvwgk** [comment]
Since the eigenvalues are the Fock matrix in the MO basis, you can recover it by changing the basis from MOs to AOs.

```python
# Not tested!
import numpy as np
import tblite.interface as tb

get_fock_matrix(res: tb.Result) -> np.ndarray:
    emo = res.get("orbital-energies")
    ao_to_mo = res.get("orbital-coefficients")
    return np.einsum("ik,k,kj->ij", ao_to_mo.T, emo, ao_to_mo)
```

**Comment by linminhtoo** [comment]
> Since the eigenvalues are the Fock matrix in the MO basis, you can recover it by changing the basis from MOs to AOs.
> 
> ```python
> # Not tested!
> import numpy as np
> import tblite.interface as tb
> 
> get_fock_matrix(res: tb.Result) -> np.ndarray:
>     emo = res.get("orbital-energies")
>     ao_to_mo = res.get("orbital-coefficients")
>     return np.einsum("ik,k,kj->ij", ao_to_mo.T, emo, ao_to_mo)
> ```

Ok this makes sense!

Thank you once again :) really awesome work with this wrapper!

**Comment by linminhtoo** [comment]
hey @awvwgk ,  sorry for asking more questions.

I am in the process of re-creating the data processing pipeline for Orbnet-Equi  https://www.pnas.org/doi/10.1073/pnas.2205221119 (there's an equivalent ArXiv paper at https://arxiv.org/abs/2105.14655), because although the code is uploaded, it is missing critical components in processing new data and training the model. (if i succeed in reimplementing these parts, I plan to opensource them for the benefit of the quantum physics / scientific community, given how powerful the Orbnet-Equi architecture is)

Following your equation, I now have on hand the matrices F, H, P, S needed by the model as input feature matrices. Luckily, the Orbnet-Equi comes with an already featurised QM9 dataset in an hdf5 file, where I can retrieve molecular geometries and all the associated matrices pre-computed by the authors of Orbnet-Equi.

However, I encountered a strange behavior. The H, P and S matrices they have are very close (i.e. match) the `hamiltonian-matrix`, `density-matrix` and `overlap-matrix` in the results dictionary of `tblite`. But the fock matrix entries do not match. 

For example, here are the 1st row and 2nd column of the core hamiltonian matrix:
mine (using `tblite`, please note I re-ordered the rows & columns to reverse the ordering of p orbitals but did not change the entries)
1st row:
```
array([-0.51129589,  0.        ,  0.        ,  0.        , -0.18768129,
        0.00492059, -0.00781999, -0.25539597, -0.0199323 ,  0.01463602,
       -0.0072078 , -0.0335227 , -0.35597389,  0.00720433, -0.35332052,
        0.00819425, -0.3532754 ,  0.00821109, -0.05594551,  0.06719314])
```
2nd col: ( please note I re-ordered the rows & columns to reverse the ordering of p orbitals but did not change the entries)
```
array([ 0.00000000e+00, -3.65003031e-01,  0.00000000e+00,  0.00000000e+00,
       -4.89757512e-03, -1.20134132e-01, -2.22119256e-04, -7.25427106e-03,
       -1.67721700e-02,  1.62393936e-04, -5.95782415e-03, -2.77092036e-02,
       -2.99256528e-01, -1.09724502e-01,  2.75076636e-01,  1.00888339e-01,
        4.72419233e-02,  1.73267232e-02,  3.22118827e-02, -1.27742248e-02])
```
theirs (using their proprietary software `qcore` but essentially GFN1-xTB)
1st row:
```
array([-0.51129587, -0.        , -0.        , -0.        , -0.18768128,
        0.00492059, -0.00781999, -0.25539596, -0.0199323 ,  0.01463602,
       -0.0072078 , -0.0335227 , -0.35598439,  0.00724337, -0.35333155,
        0.00823553, -0.35328644,  0.00825241, -0.05589967,  0.06698566])
```
2nd col:
```
array([-0.00000000e+00, -3.65003015e-01, -0.00000000e+00, -0.00000000e+00,
       -4.89757490e-03, -1.20134127e-01, -2.22119246e-04, -7.25427074e-03,
       -1.67721693e-02,  1.62393928e-04, -5.95782389e-03, -2.77092024e-02,
       -2.99226112e-01, -1.09831365e-01,  2.75046368e-01,  1.00995251e-01,
        4.72367183e-02,  1.73451097e-02,  3.21818499e-02, -1.26594623e-02])
```

despite some slight numerical differences, I think these are essentially identical, which is a good sign.
I also compared the `orbital-energies` vector for this molecule, and they also match up very closely. 

in comparison, here are the entries of the fock matrix:
mine:
1st row: ( please note I re-ordered the rows & columns to reverse the ordering of p orbitals but did not change the entries)
```
array([ 0.38401068, -0.02367831,  0.01356861,  0.14414845, -0.04684769,
        0.03034643, -0.01891142, -0.24604234, -0.09213378,  0.0676193 ,
       -0.02887127,  0.0444452 , -0.36610915, -0.21754102, -0.36624499,
       -0.22431615, -0.3661063 , -0.22429794, -0.01548635, -0.02756553])
```
2nd col: ( please note I re-ordered the rows & columns to reverse the ordering of p orbitals but did not change the entries)
```
array([-0.02367831,  0.12581509, -0.0220674 ,  0.0164267 , -0.05859212,
       -0.20526513,  0.05631715,  0.03820901,  0.12836358, -0.08199155,
        0.05288011,  0.07918232, -0.36779461, -0.09211799,  0.33112424,
        0.08638055,  0.07643326,  0.02478718, -0.0850532 , -0.02169113])
```

theirs:
1st row:
```
array([-0.54811897,  0.        ,  0.        ,  0.        , -0.19963779,
        0.00521013, -0.00828015, -0.27042421, -0.01891226,  0.01392087,
       -0.00685561, -0.03188469, -0.36918417,  0.00757016, -0.36940028,
        0.00869123, -0.36935137,  0.008709  , -0.05870455,  0.07107524])
```
2nd col:
```
array([ 0.00000000e+00, -4.01334070e-01,  0.00000000e+00,  0.00000000e+00,
       -5.19471662e-03, -1.27325646e-01, -2.35415841e-04, -7.68852892e-03,
       -1.60018707e-02,  1.54832113e-04, -5.68039995e-03, -2.64189332e-02,
       -3.09952015e-01, -1.15371184e-01,  2.87154887e-01,  1.07251589e-01,
        4.93160120e-02,  1.84194635e-02,  3.36896876e-02, -1.34940860e-02])
```

as you can see, the entries are very different.

in section 1.2 of their ArXiv paper, equation 33, they define Fock matrix in a specific way. 
```math
\textbf{F} = \textbf{H} + \textbf{G} [\textbf{P}]
```
where H is the one-electron integrals including electron-nuclear attraction and electron kinetic energy. G is the two-electron
integrals comprising the electron-electron repulsion. Approximation of G is the key task for self-consistent field
methods, and GFN-xTB provides an accurate and efficient tight-binding approximation for G. 

But to me, it doesn't seem anything out of the ordinary. The strangest thing is that the H, P and S matrices they have are very close (i.e. match) the `hamiltonian-matrix`, `density-matrix` and `overlap-matrix` in the results dictionary of `tblite`. Surely, this cannot be a coincidence.

Here is the full geometry and full fock matrices of the molecule, if it helps: https://gist.github.com/linminhtoo/2ae2dbb965224b03e8eb2ffdced710a0

I understand this is way beyond the scope of maintaining `tblite`, but I'm hoping if you happen to have any additional insight into this problem, since you're clearly an expert at the `xTB` method. Any ideas or thoughts would be greatly appreciated!

Thank you once again.

**Comment by awvwgk** [comment]
I checked my function for computing the Fockian by replacing the eigenvalues with the occupation and can recover the density matrix up to some numerical noise (1e-15).

In the uploaded example the dimensions of the two matrices are mismatched, therefore I cannot check those quickly now.

**Comment by linminhtoo** [comment]
> I checked my function for computing the Fockian by replacing the eigenvalues with the occupation and can recover the density matrix up to some numerical noise (1e-15).
> 
> In the uploaded example the dimensions of the two matrices are mismatched, therefore I cannot check those quickly now.

I see, that's reassuring to an extent.

And I just realised I pasted the wrong fock matrix for "their" matrix. I have edited the gist to reflect the correct 20x20 matrix they have. My bad, and thanks again!
