### ISSUE TITLE
Properties do not appear to be affected by `Atoms.get_initial_magnetic_moments()`

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [tblite/tblite#111]
As in the [`xtb-python` ASE interface](https://github.com/grimme-lab/xtb-python/issues/42), one would assume that the ASE calculator interface for `tblite` would set the spin multiplicity of the system based on the provide initial magnetic moments.

Based on the example below, one would expect that if the spin multiplicity is correctly set, then `e1 != e2`. However, the two values are the same after running the code, indicating that changing the initial magnetic moments does not change the total energy.

```python
from tblite.ase import TBLite
from ase.build import molecule

atoms1 = molecule("CH3")
assert atoms1.get_initial_magnetic_moments().sum() == 1
atoms1.calc = TBLite()
e1 = atoms1.get_potential_energy()

atoms2 = molecule("CH3")
atoms2.set_initial_magnetic_moments([0] * len(atoms2))
assert atoms2.get_initial_magnetic_moments().sum() == 0
atoms2.calc = TBLite()
e2 = atoms2.get_potential_energy()

print(e1, e2)
```

Output:
```
-96.94687655923573 -96.94687655923572
```

I'm confused because the code does suggest that the `_uhf` parameter is being set:

https://github.com/tblite/tblite/blob/b3dcf324366eb053d41bd15af15b4a2d26487a4a/python/tblite/ase.py#L221-L231

However, even if you set the initial magnetic moments to 100, you still get the same answer for the energy suggesting that it's not making a difference.

**Comment by haneug** [comment]
I have no experience with the ASE interface, but if the spin multiplicity you request can not be realized the given multiplicity is ignored (at least in calculations with the tblite stand-alone). Magnetic moments of 0 or 100 are not possible for CH3 (An uneven number of electrons can not yield a closed shell configuration, and 100 is not possible because you do not have that many electrons available). Maybe try 1 and 3 instead?

**Comment by Andrew-S-Rosen** [comment]
@haneug --- Thank you!! You are right! 

```python
from tblite.ase import TBLite
from ase.build import molecule

atoms1 = molecule("CH3")
assert atoms1.get_initial_magnetic_moments().sum() == 1
atoms1.calc = TBLite()
e1 = atoms1.get_potential_energy()

atoms2 = molecule("CH3")
atoms2.set_initial_magnetic_moments([3, 0, 0, 0])
assert atoms2.get_initial_magnetic_moments().sum() == 3
atoms2.calc = TBLite()
e2 = atoms2.get_potential_energy()

print(e1, e2)
```

Returns
-96.94687655923558 -81.03056596288175

I guess by default, `tblite` was changing the (impossible) initial magnetic moment of 0 to 1 silently, which is why the two energies were the same in my original example.
