### ISSUE TITLE
Suggestion: Raise warning in ASE calculator if `_uhf` is not valid

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [tblite/tblite#112]
The ASE calculator sets the `_uhf` parameter as follows:

https://github.com/tblite/tblite/blob/b3dcf324366eb053d41bd15af15b4a2d26487a4a/python/tblite/ase.py#L217-L231

However, as described in #111, if the value for `_uhf` is invalid given the number of electrons in the molecule, no warnings or errors are raised. For instance, a CH3 molecule with 0 initial magnetic moments will run without any error or warning to the user (and in fact, I think `tblite` automatically sets it to `_uhf` 1 internally). This can lead to unexpected behavior.

I propose that a `UserWarning` should be raised if `_uhf` is ultimately going to be ignored by the `tblite` executable.

**Comment by awvwgk** [comment]
The check for the right number of unpaired electrons is implemented for the single point driver at

https://github.com/tblite/tblite/blob/f7bedab33bca52d3fe07f2418bc9008ef3c4effe/src/tblite/xtb/singlepoint.f90#L184-L189

by default this number is only used if reasonable and dropped if not further specified.
