### ISSUE TITLE
Pip install support for Mac and (stretch goal) Windows

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [tblite/tblite#115]
Doing `pip install tblite[ase]` on Mac gets:

```
      ../../subprojects/tblite/config/meson.build:46:12: ERROR: Dependency "openmp" not found, tried system
```

It would be great to have more native support for this.

If this can be done via the `conda-forge` package, what is the appropriate command to install `tblite[ase]` (i.e. tblite with ASE calculator support)?

**Comment by awvwgk** [comment]
Except for Windows all platforms should be available at https://github.com/conda-forge/tblite-python-feedstock

**Comment by awvwgk** [comment]
Note that the error you are seeing is expected with pip on MacOS as the default C compiler does not support OpenMP, better use a compiler (from brew or conda, set via ``CC`` and ``FC`` env vars) which provides the necessary requirements.

**Comment by Andrew-S-Rosen** [comment]
Tagging @janosh here. Thanks for the reply! Is `tblite-python` the appropriate conda-forge route for also installing tblite with ASE calculator support?

**Comment by janosh** [comment]
I ran

```
brew install gcc
CC=gcc-12 pip install 'tblite[ase]'
```

which throws

```
      gfortran -Isubprojects/mctc-lib/libmctc-lib.a.p -Isubprojects/mctc-lib -I../../subprojects/mctc-lib -I../../subprojects/mctc-lib/include -Isubprojects/json-fortran-8.2.5/libjsonfortran.a.p -fdiagnostics-color=always -DNDEBUG -Wall -O3 -ffree-line-length-none -fbacktrace -DWITH_JSON=1 -Jsubprojects/mctc-lib/libmctc-lib.a.p -o subprojects/mctc-lib/libmctc-lib.a.p/src_mctc_io.f90.o -c ../../subprojects/mctc-lib/src/mctc/io.f90
      /bin/sh: gfortran: command not found
      ninja: build stopped: subcommand failed.
```

I thought `gfortran` comes with `gcc`?

**Comment by awvwgk** [comment]
Try setting ``FC=gfortran-12`` as well?

**Comment by awvwgk** [comment]
Yes, you can install `tblite-python` and `ase` to use the provided calculator.

**Comment by janosh** [comment]
> Try setting FC=gfortran-12 as well?

Yeah I tried that. More errors. Maybe my system is messed up...

But not super important. If `tblite-python` serves our purpose, I think we're good.

**Comment by awvwgk** [comment]
Can't help with errors if I don't get to see the actual error messages. Happy if the cf dist is sufficient.

**Comment by awvwgk** [comment]
I am adding Windows support to tblite on cf right now: https://github.com/conda-forge/tblite-python-feedstock/pull/15. Also, for PyPI we now have wheels for MacOS (Arm only) as well.
