### ISSUE TITLE
`tblite` does not work properly if installed alongside `torch-2.0.1`

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [tblite/tblite#116]
I am getting SCF convergence errors on a simple ASE-based static calculation on CH4 when `tblite[ase]==0.3.0` is installed alongside `torch-2.0.1`. No SCF convergence errors are found without `torch`. I am still investigating.

**Comment by Andrew-S-Rosen** [comment]
Edit: I think this is the same as #110, except switching the import order doesn't fix it for me.

**Comment by SingletC** [comment]
if you need direction, check OMP/MKL lib

**Comment by awvwgk** [comment]
Duplicate of #110.
