### ISSUE TITLE
Solvent and GFN-FF support

### ISSUE THREAD

**Issue by mgt16-LANL** [tblite/tblite#129]
Hi All,

After realizing TBLite is now the recommended upgrade from xtb-python, I noticed two features that can play a prominent role in my existing workflows are missing from TBLite that were implemented in xtb-python (particularly in the ASE interface) that I haven't seen another issue raised on: 1. implicit solvent effects 2. GFN-FF support. It would seem that adding support for 1 should be easier, but 2 might require a different library interface. Are there any plans to implement these features?

Cheers,
Michael.

**Comment by samblau** [comment]
Seconding this - adding support for implicit solvation would also be immediately impactful for my work!

**Comment by ViktoriiaBaib** [comment]
+1 for implicit solvent! Very much needed in my project.

**Comment by pitsteinbach** [comment]
Hey there,

I will get to the addition of the CPCM and ALPB models to the python API.
GFN-FF is another story and would mean more work and probably the addition of another subproject to tblite.

Best
Pit
