### ISSUE TITLE
The tblite ASE calculator interface does not properly handle `KeyboardException` (Ctrl+C)

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [tblite/tblite#134]
When running a structure relaxation using ASE and tblite, doing Ctrl+C (keyboard interrupt) cancels the current cycle but not the run as a whole. This makes it very difficult and inconvenient to abort a run.

```python
from tblite.ase import TBLite
from ase.build import bulk
from ase.optimize import BFGS

atoms = bulk("Cu")*(3,3,3)
atoms.calc = TBLite()
dyn = BFGS(atoms)
dyn.run(fmax=1e-4)
```

Then Ctrl+C before it finished. Tested on tblite 0.3.0.

![image](https://github.com/tblite/tblite/assets/8674072/37847601-ed09-4836-9ebc-5a5ad43c5320)

**Comment by awvwgk** [comment]
The logging for the Python API is implemented in a callback to Python, the exception must be caught and suppressed, otherwise we leave the Fortran runtime in an undefined state. Maybe we can propagate the error to the API context and stop the calculation gracefully.
