### ISSUE TITLE
More open licenses for the API

### ISSUE THREAD

**Issue by HaoZeke** [tblite/tblite#136]
Mirrors https://github.com/grimme-lab/xtb/issues/901, where @MtoLStoN mentioned that `tblite` should cover the usage requirements (essentially single point calculations). Cloning the relevant parts of the issue here:

**Is your feature request related to a problem? Please describe.**

I have a BSD-3 clause licensed code  (a new version of [eON](https://theory.cm.utexas.edu/eon/)). I would like to keep it that way. However, since it is in C++, I would like to use the C-API instead of using an I/O interface (which is the only option currently compatible with the licenses). I believe [ORCA](https://theory.cm.utexas.edu/eon/) could also do a better job than its current I/O interface if the API was better licensed.

**Describe the solution you'd like**
It would be best to use a non-viral license (e.g. MIT) for the C-API (the [tblite.h file](https://github.com/tblite/tblite/blob/main/include/tblite.h)), since that way it could be integrated better. 

**Describe alternatives you've considered**
As noted, the simplest option here is to interface via system calls (sometimes even just directly to STDOUT), followed by some I/O. This is slow and cumbersome, but compatible with the license.

**If possible state how you can assist in providing data or code to to implement the feature**
I'd be happy to discuss this further and could of course open a PR to change the license but it is really for project maintainers to decide.

**Additional context**
The API should be meant to be vendored in third party codes, and the onus should be simply on the user to ensure they are able to build against `tblite` when they compile the codes jointly.

Of course this means binaries will still not include `tblite`, just the interface (downstream projects have to figure out their own guards for this).

**Comment by awvwgk** [comment]
I don't exactly see why there would be issues when using tblite as a library via the LGPL. This project does depend on other libraries with the same license and I am currently not convinced that relicensing would actually be necessary.

**Comment by HaoZeke** [comment]
> I don't exactly see why there would be issues when using tblite as a library via the LGPL. This project does depend on other libraries with the same license and I am currently not convinced that relicensing would actually be necessary.

Files under the LGPL cannot be (as I understand) "vendored" in. This means it cannot be distributed as-is. If the API was MIT licensed, then it could be added as a single file to any distribution (the user would still have to download the rest of `tblite` but that's on them). Currently, I'd have to instruct users to get the header file at a version and the code at the same version. If I vendored the header file I could do a runtime check for the API version.

**Comment by awvwgk** [comment]
I don't exactly understand why files from tblite need to be vendored. I guess it is easy enough to find the tblite header from an installed library or fetch the dependency as necessary. There are many options for vendoring the header file if necessary, for example to make building this part of the code base optional. Of course the repository must track where vendored files were taken from and what their licenses are, even with relicensing tblite this would still be necessary.
