### ISSUE TITLE
Different solvation energies in tblite and xtb

### ISSUE THREAD

**Issue by Trebonius91** [tblite/tblite#138]
Hi together,

I have noticed that application of both ALPB and GBSA solvation models resulted in different energies for the newest versions of tblite (the installed executable after building with meson) and xtb.
A simple example is a single point calculation of ethanol (ethanol.xyz):

    9    
    Ethanol
      H      1.8853     -0.0401      1.0854
      C      1.2699     -0.0477      0.1772
      H      1.5840      0.8007     -0.4449
      H      1.5089     -0.9636     -0.3791
      C     -0.2033      0.0282      0.5345
      H     -0.4993     -0.8287      1.1714
      H     -0.4235      0.9513      1.1064
      O     -0.9394      0.0157     -0.6674
      H     -1.8540      0.0626     -0.4252

Without solvation, both programs essentially give the same energy (as expected):

    tblite ethanol.xyz

resulted in:

    ....
    ------------------------------------------------------------
      cycle        total energy    energy error   density error
    ------------------------------------------------------------
          1     -11.34484894099  -1.1462750E+01   1.6126437E-01
          2     -11.38501140154  -4.0162461E-02   7.2796973E-02
          3     -11.39038158210  -5.3701806E-03   2.0933834E-02
          4     -11.39068145220  -2.9987011E-04   1.0279824E-02
          5     -11.39074527592  -6.3823713E-05   1.8471074E-03
          6     -11.39075016731  -4.8913914E-06   9.5529263E-04
          7     -11.39075043232  -2.6501404E-07   3.7627198E-04
          8     -11.39075091328  -4.8096264E-07   1.4263204E-04
          9     -11.39075096916  -5.5874589E-08   9.6098618E-06
    ------------------------------------------------------------

    electronic energy        -1.1508651630483E+01 Eh
    total energy             -1.1390750969159E+01 Eh
    ....

and 

    xtb ethanol.xyz

resulted in:

               -------------------------------------------------
              | TOTAL ENERGY              -11.390750963714 Eh   |
              | GRADIENT NORM               0.185597446632 Eh/α |
              | HOMO-LUMO GAP              12.836665182229 eV   |
               -------------------------------------------------

When applying ALPB with water as solvent, however, the results are different:

    tblite ethanol.xyz --alpb water

gives 

    -11.39322361699 Eh

but 

    xtb  ethanol.xyz --alpb water

gives

    -11.397759549872 Eh

Thus, the solvation energy seems more than twice as large for the xtb program as in the case of tblite, even if the same structure is calculated with the same solvation model. Similar deviations can be observed by using GBSA.

I therefore wanted to ask if there are some different default settings for both programs which must be changed by the user to get the same results or if there is some issue with the solvation in tblite in general.

Thanks in advance!

**Comment by haneug** [comment]
Indeed, ALPB and GBSA are implemented without any empiric parameters and only the polar contributions to the solvation free energy. The non-polar terms are also implemented but not in use. In principle, only the empiric parameters have to be added and the cds term has to be turned on. I will see if I can find the time to add this.
