### ISSUE TITLE
Program parallelism

### ISSUE THREAD

**Issue by Phorbol** [tblite/tblite#139]
I cannot find the method to use n cores in tblite ase calculator in manual and tutorial. Maybe I should use the environment variable such as XTB --help says：
export MKL_NUM_THREADS=<NCORE>
export OMP_NUM_THREADS=<NCORE>,1
export OMP_STACKSIZE=4G
ulimit -s unlimited
？

**Comment by pitsteinbach** [comment]
Hey, 
yes you can control the parallelization behavior, both OMP and BLAS/LAPACK-related by environment variables.
If you have chosen another BLAS/LAPACK package than MKL, you might want to set the appropriate environment variable, like `OPENBLAS_NUM_THREADS=4`.

**Comment by pitsteinbach** [comment]
Hey @Phorbol, is their still a problem or can we close this issue?

**Comment by Phorbol** [comment]
Yeah, thank you very much and Merry Christmas. But I want to control it in python. By the way, will you develop this feature in the future versions?

**Comment by pitsteinbach** [comment]
Merry Christmas to you as well. You can control environment variables in python by using `os.environ` here is the [link](https://docs.python.org/3/library/os.html) to their documentation. This allows you to set the variables controlling tblite's parallel execution. As for `ulimit -s unlimited` you could use the `resource` [module](https://docs.python.org/3/library/resource.html#resource-limits), however I have not tested the latter.
Let me know if this covers the desired functionality.

**Comment by Phorbol** [comment]
Okay, that's how I understood and operated before.  My idea may like 
`atoms.calc = TBLite(ncores=n)`
, but the `os.environ` method is also ok.
By the way, I'm interested in the XTB Force Field  using in ase, looking forward to your future developments.
Thank you and I'll close the issue.
