### ISSUE TITLE
Compilation issue, stuck at lapack

### ISSUE THREAD

**Issue by MarcMignolet** [tblite/tblite#147]
I have been trying to install tblite on windows but I am stuck with an error regarding lapack. I am attaching the log file. Could someone help?
I am new at this and stuck....
Thank you!
[meson-log.txt](https://github.com/tblite/tblite/files/13824054/meson-log.txt)

**Comment by awvwgk** [comment]
You need to provide a LAPACK implementation to build tblite. I am not sure what your current setup looks like, therefore it is hard to provide advice for this issue. Do you have LAPACK installed and it just not found by meson?

**Comment by MarcMignolet** [comment]
As per the install instructions, I have downloaded Windows x64 OpenBLAS binaries via https://sourceforge.net/projects/openblas/files/. Is this sufficient?

**Comment by awvwgk** [comment]
No it is not as the installation cannot be found by meson. You need to make the location of OpenBLAS known to meson, for example by adjusting the search paths for libraries.
