### ISSUE TITLE
Discrepancies in Orbital Energies between tblite Calculator and Stand-alone xtb

### ISSUE THREAD

**Issue by blaschma** [tblite/tblite#156]
Hi,
thank you for the beautiful project. However, I've encountered a few issues. When using the tblite calculator (b48a84fc8fe7641d352f7c2813a8eab99d19dc2b) for GFN1-xTB/GFN2-xTB, I observed variations in orbital energies compared to the stand-alone xtb (tested with xtb version 6.6.1, commit hash: 8d0f1dd).

Here's an example for H2O:
```
pos = np.array([[0, 0.81817, 0],[0, - 0.40860, 0], [0, - 0.32333, 0.97000]])
atoms = np.array([8, 1, 1])
calc = Calculator(
    method="GFN1-xTB",
    numbers=atoms,
    positions=pos,
)
res = calc.singlepoint()
e = res.get("orbital-energies")
```
For the HOMO/LUMO energies this results into -1.330714686302447802e+01 eV and -4.024812142355524536e+00 eV. However, the stand-alone xtb gives different values (Energy in the left column (eV)): 
```
         4        2.0000           -0.4986360             -13.5686 (HOMO)
         5                         -0.1570446              -4.2734 (LUMO)
```
While the deviation for this molecule is relatively small, more complex molecules exhibit significant discrepancies. For example, in 1,4-BENZENEDITHIOL, the values of HOMO energies deviate approximately 4 eV. Do you know why that is?
Thank you.

**Comment by haneug** [comment]
Both xtb and tblite internally use Bohr as a length unit. When using the API be sure to do the conversion from Angstrom first, the CLI for both programs will do the conversion for you if an XYZ file is provided as input.

**Comment by blaschma** [comment]
Thank you! Problem solved.
