### ISSUE TITLE
Providing info on parallelization with `tblite` in the documentation

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [tblite/tblite#166]
It'd likely be worthwhile to provide some bare-bones information about various parallelization settings for `tblite` in the case of people using it as a standalone utility. It can honestly be as simple as pointing to the [corresponding section](https://xtb-docs.readthedocs.io/en/latest/setup.html#parallelisation) in the `xtb` docs since I imagine those OpenMP parameters are just as relevant here. This is related to https://github.com/tblite/tblite/issues/139.

In particular, the `export OMP_STACKSIZE` is pretty important to prevent segfaults.

**Comment by pitsteinbach** [comment]
Thanks for the input, I will include those instructions into the documentation and add also the information from #139 regarding parallelization when using the python API.
