### ISSUE TITLE
Request: Add ASE interface in the next conda build

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [tblite/tblite#176]
Currently, doing `conda install -c conda-forge tblite` does not install TBLite with ASE support. This is fine for Linux users who can do `pip install tblite[ase]`, but for Max users where the `pip` install doesn't work, they can only get ASE support by building from source. It would be really great if the next `conda` build had an option for ASE support.

**Comment by awvwgk** [comment]
Does the tblite-python package not provide the ASE calculator already?

**Comment by Andrew-S-Rosen** [comment]
Huh, all this time and I never knew that existed. Indeed, it does!!!
