### ISSUE TITLE
Error installing with PIP

### ISSUE THREAD

**Issue by icamps** [tblite/tblite#195]
Hi.

I am trying to install `tblite` with PIP but I am getting some errors that I couldn't find the origin. The log file indicated to be in the tmp folder, is deleted after the installation.

Here I  am attaching the log from the `pip install tblite` command:

[tblite_error.txt](https://github.com/user-attachments/files/16529740/tblite_error.txt)

Regards.

**Comment by awvwgk** [comment]
~~Duplicate of #175~~

Similar issue was observed with https://github.com/dftd3/simple-dftd3/issues/62 and Python 3.12, the issue does not exist for builds on conda-forge but only for builds in pip.
