### ISSUE TITLE
GFN-FF support

### ISSUE THREAD

**Issue by SolalAttiasInstadeep** [tblite/tblite#201]
Hi,

Some bugs are preventing me from working with xtb-python and its ASE interface, and as tblite seems to be the recommended upgrade, I am checking it out. However, in my project I wish to use GFN-FF. I see that issue #129 requested the feature as well as implicit solvent effects, but was closed as the second was implemented. I would thus like to probe and see if there are plans to implement GFN-FF!

Thanks!

**Comment by awvwgk** [comment]
A standalone version of the GFN-FF is provided in https://github.com/pprcht/gfnff which is used by CREST to implement the GFN-FF outside of *xtb*. For *tblite* however I am not sure how much in scope GFN-FF support would be here.

If there is support from the GFN-FF developers to support the method in a library first way as provided by *tblite* it might be possible to integrate in the framework of this library. For now this seems to be out of scope for *tblite* itself and I would close this as not planned.

However, for *xtb-python* a way forward would be to drop the dependency on *xtb* and instead use *tblite*'s Python API together with the GFN-FF standalone library to implement a more stable Python API.
