### ISSUE TITLE
Installation issue on Mac: pip install tblite

### ISSUE THREAD

**Issue by V-Alizade** [tblite/tblite#205]
It seems installing tblite with pip is not supporting Mac, this comes up with trying to install tblite for ipi-xtb interface, please see https://github.com/i-pi/i-pi/pull/376.

**Comment by awvwgk** [comment]
Thanks for the report. For pip we currently only have pre-built wheels for Linux available. For the next release we might be able to have wheels for OSX as well.

In the meantime the recommended way to get tblite on OSX would be via mamba.
