### ISSUE TITLE
Warnings and test errors when static linking

### ISSUE THREAD

**Issue by npe1011** [tblite/tblite#208]
I tried building on several envirionments:
1. Docker (Ubuntu 20.04 + gcc9 + openblas)
2. Docker (Ubuntu 24.04 + gcc13 + openblas)
3. Docker (intel/hpckit 2024)
4. Docker (intel/oneapi-hpckit 2023)
5. RHEL-based Linux workstation or cluster (several intel compilers as well as gcc 8.5)

In most cases, meson build without static link options suceeded and the binary works fine. But when -Dfortran_link_args=-static --default-library=static options were used, I saw many warnings like:
Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking.
In those cases, many tests failed with memory errors (SIGSEGV 11).

**Comment by awvwgk** [comment]
Thanks for reporting, I haven't linked tblite into static binaries in a long time now, but rather relied on dependencies managed via mamba. For me personally, static linking as a priority feature in tblite has become less relevant, however it would still be nice for it to just work, maybe provided by continuous delivery.

From this report, is there anything actionable on the side of tblite to do? Feel free to open a new issue with the detailed test failure to allow reproducing the issue.
