### ISSUE TITLE
Tblite-python ASE-API spin_polarization question

### ISSUE THREAD

**Issue by Phorbol** [tblite/tblite#213]
I want to use ASE API to implement scan and NEB calculations, which there may be some spin change during scan or NEB process and it's not very clear to predict the multiplicity, and in quantum chemistry program, this problem can solve such as by ISPIN=2(VASP) or UKS method(Gaussian).
So I want to know that whether exists a method to solve problems above, and after reading manual, I'm not sure what the exact way spin_polarization parameter should be written.
Thank you very much!

**Comment by Phorbol** [comment]
Another question, I'm not sure the ability to describe dispersive interactions of gfn2-xtb method, and I want to learn the dispersive interactions is from DFT-D3/D4 or not?
Thank you!

**Comment by Phorbol** [comment]
By my test, O2 molecule in ASE, if give initial magmom guess 2 * 1, comparing the multiplicity=3, energy change is about 0.072 eV, and I'm confused the spin_polarization value how effect the calculation

**Comment by thfroitzheim** [comment]
Hi, 

the spin_polarization feature in tblite includes an explicitly spin-dependent term in an unrestricted calculation (based on the magnetization and not just the density, see [here](https://doi.org/10.1002/jcc.27185) for the details). So activating spin_polarization will impact only those calculations with an open-shell electronic structure (i.e. a triplet) and differentiates the low- and high-spin states further. The required parameters are already present in the tblite (based on PBE). Still, you have to define the multiplicity for every calculation (and potentially try all important multiplicities if they are close). 

Concerning Dispersion, GFN2 employs self-consistently the DFT-D4 correction. 

Hope I could help, 
Thomas

**Comment by awvwgk** [comment]
Closing this as resolved and answered. Please feel free to open a new issue if anything remains unclear.
