### ISSUE TITLE
How to get the Hamiltonian matrix?

### ISSUE THREAD

**Issue by zwei-beiner** [tblite/tblite#214]
Hi, I'm trying to get the Hamiltonian matrix. The following code from the docs works fine:
```python
from tblite.interface import Calculator
import numpy as np
numbers = np.array([1, 1, 6, 5, 1, 15, 8, 17, 13, 15, 5, 1, 9, 15, 1, 15])
positions = np.array([  # Coordinates in Bohr
    [+2.79274810283778, +3.82998228828316, -2.79287054959216],
    [-1.43447454186833, +0.43418729987882, +5.53854345129809],
    [-3.26268343665218, -2.50644032426151, -1.56631149351046],
    [+2.14548759959147, -0.88798018953965, -2.24592534506187],
    [-4.30233097423181, -3.93631518670031, -0.48930754109119],
    [+0.06107643564880, -3.82467931731366, -2.22333344469482],
    [+0.41168550401858, +0.58105573172764, +5.56854609916143],
    [+4.41363836635653, +3.92515871809283, +2.57961724984000],
    [+1.33707758998700, +1.40194471661647, +1.97530004949523],
    [+3.08342709834868, +1.72520024666801, -4.42666116106828],
    [-3.02346932078505, +0.04438199934191, -0.27636197425010],
    [+1.11508390868455, -0.97617412809198, +6.25462847718180],
    [+0.61938955433011, +2.17903547389232, -6.21279842416963],
    [-2.67491681346835, +3.00175899761859, +1.05038813614845],
    [-4.13181080289514, -2.34226739863660, -3.44356159392859],
    [+2.85007173009739, -2.64884892757600, +0.71010806424206],
])
calc = Calculator("GFN2-xTB", numbers, positions)
res = calc.singlepoint()
res.get("energy")  # Results in atomic units
```

However, when I call
```python
res.get("hamiltonian-matrix")
```

I get the error `RuntimeError: Result does not contain Hamiltonian matrix`.

**Comment by awvwgk** [comment]
You need to request the Hamiltonian explicitly by using
```
calc.set("save-integrals", True)
```
Before running the single point calculation

**Comment by zwei-beiner** [comment]
Thank you, that works now.

**Comment by zwei-beiner** [comment]
Just to check, are the following definitions correct? (I could not find them in the docs and this is my first time using a tight-binding code.)
- The `orbital-coefficients` matrix $C$ contains $c_{\mu i}=\langle \phi_\mu |\psi_i\rangle$, where $|\psi_i\rangle=\sum_\mu c_{\mu i}|\phi_\mu\rangle$ and $|\psi_i\rangle$ is the MO and $|\phi_\mu \rangle$ the AO basis.
- The `hamiltonian-matrix` $h$ contains $\langle\phi_\mu |H| \phi_\nu\rangle$, so to switch to the converged full Hamiltonian after self-consistency, we have to compute $\langle\psi_i |H| \psi_j \rangle=\sum_{\mu\nu}c_{\mu i}^* c_{\nu j} \langle\phi_\mu |H| \phi_\nu\rangle=C^\dagger h C$.
- The `overlap-matrix` contains $\langle\psi_i|\psi_j\rangle$.

And is there any way of obtaining the Hamiltonian before the self-consistent iterations are performed?

**Comment by awvwgk** [comment]
The `hamiltonian-matrix` is the core Hamiltonian. To recover the converged Hamiltonian you can reconstruct the full Hamiltonian matrix from the eigenvalues and orbital coefficients.
