### ISSUE TITLE
Wavefunction set as inital guess

### ISSUE THREAD

**Issue by RuochengHan** [tblite/tblite#219]
Dear developers,
Is there any plan to set wavefunction (orbital coef. from an old calculation) as an initial guess for the new one?
E.g. a customed geometry optimization/MD would need the wavefunction from the previous step to accelerate the convergence of wavefunction.

Related: https://github.com/tblite/tblite/issues/165

**Comment by awvwgk** [comment]
That would be a useful feature to have indeed. What is missing is indeed #165 for this to work.

I see the main challenge on defining a sane restarting behavior if incompatible properties are provided, e.g. if shell charges from GFN2-xTB are provided for GFN1-xTB or if we only provide atomic charges and need to create shell charges from them. For a first implementation, we could either fail on those with an error or drop the unusable guess.

**Comment by RuochengHan** [comment]
> That would be a useful feature to have indeed. What is missing is indeed #165 for this to work.
> 
> I see the main challenge on defining a sane restarting behavior if incompatible properties are provided, e.g. if shell charges from GFN2-xTB are provided for GFN1-xTB or if we only provide atomic charges and need to create shell charges from them. For a first implementation, we could either fail on those with an error or drop the unusable guess.

Ah, I never thought about cross-linking different methods, indeed their basis functions are even different. This potentially helps me implement methods in geometry optimization/MD steps (methodology development so cannot use the default engine), when the coefficient does not change much in a small step.

**Comment by RuochengHan** [comment]
I occasionally found that in the manual:
https://tblite.readthedocs.io/en/latest/api/python.html#tblite.interface.Result
restart is supported and it is exactly what I mean in this issue:
```python
prev_results = calc.singlepoint()
results = calc.singlepoint(prev_results)
```
Therefore, I would like to close this issue. 

But I agree that this does not work for a cross-method restart as @awvwgk said.

**Comment by awvwgk** [comment]
In https://github.com/tblite/tblite/pull/277 the Python API includes a features to write or read the restart information as npz file. In principle an external program can provide the relevant data in the npz file and tblite will be able to pick it up and run the calculation from the provided data.
