### ISSUE TITLE
Minor error in calculation of Born radii

### ISSUE THREAD

**Issue by marvinfriede** [tblite/tblite#63]
One of the adjustable parameters of the GB-OBC model is incorrect: `obc(3)` is used twice.

https://github.com/tblite/tblite/blob/dcfb318786da910466e2b08c0a207f3ee820c4ad/src/tblite/solvation/born.f90#L177

It should be: `arg2 = br*(obc(3)*br-obc(2))`. I did not create a PR as this breaks tests and I wasn't quite sure on how to obtain the reference radii.

**Comment by awvwgk** [comment]
Good catch, this seems to be indeed in error. Breaking the tests is secondary if we fix a faulty implementation. Recalculating and updating the references is a bit more tedious.
