### ISSUE TITLE
Obtain more properties via python api

### ISSUE THREAD

**Issue by jackwebersdgr** [tblite/tblite#77]
On the regular xtb documentation it can print out multiple properties, including bond orders, dispersion coefficients, and polarizability (https://xtb-docs.readthedocs.io/en/latest/properties.html?highlight=dispersion#gfn2-xtb), which are not implemented in the python API on tblite. Are there plans to add these properties to tblite?

**Comment by awvwgk** [comment]
The dispersion coefficients and polarizibilities can be obtained from the [`dftd4` Python module](https://dftd4.readthedocs.io/en/latest/reference/python.html#dftd4.interface.DispersionModel.get_properties). If you have the `tblite` Python API available, you already have the `dftd4` C API around and can install the Python bindings on top (`dftd4-python` from conda-forge or `pip install -s dftd4` from PyPI).

Bond orders are indeed not available at the moment, but should be straight-forward to calculate in the API. The post-processing after the single point calculation happens at

https://github.com/tblite/tblite/blob/e91b79dc050927201d3e411529d09a0b9f39a19a/src/tblite/api/calculator.f90#L540-L543

Calculating bond orders here would require access to the overlap and density matrix (having activated the `save-integrals` option). Alternatively, the bond orders could be added as entry to the wavefunction at

https://github.com/tblite/tblite/blob/e91b79dc050927201d3e411529d09a0b9f39a19a/src/tblite/wavefunction/type.f90#L30-L31

or preferably the results container at

https://github.com/tblite/tblite/blob/e91b79dc050927201d3e411529d09a0b9f39a19a/src/tblite/results.f90#L27-L28

The bond orders could be calculated after the self-consistent iterations have finished, around the place where we also currently save the integrals (if requested):

https://github.com/tblite/tblite/blob/e91b79dc050927201d3e411529d09a0b9f39a19a/src/tblite/xtb/singlepoint.f90#L319-L322
