### ISSUE TITLE
Read .CHRG / .UHF from dirname of coordinate file

### ISSUE THREAD

**Issue by awvwgk** [tblite/tblite#81]
Like in `xtb` the `.CHRG` and `.UHF` files can be used to specify the total charge and number of unpaired electrons, respectively. However, this behavior seems somewhat uninituitive in case a path to a coordinate file is given while `.CHRG` / `.UHF` can only be in the working directory.

https://github.com/tblite/tblite/blob/5db81ccb2d85014ffcff8931597d41f1fcbf16c1/app/driver_run.f90#L93-L105

An alternative implementation using the dirname of the coordinate file can be found in [`mctc-convert`](https://github.com/grimme-lab/mctc-lib/blob/cc30341ec6a6c319489c4b4b5f7f2178db7a142d/app/main.f90#L78-L90).

cc @marvinfriede

**Comment by hoelzerC** [comment]
Doesn't the [mctc-convert](https://github.com/grimme-lab/mctc-lib/blob/cc30341ec6a6c319489c4b4b5f7f2178db7a142d/app/main.f90#L78-L90) implementation solve the issue?

Looks like a straight-forward solution:
`filename = join(dirname(input), ".CHRG")`

**Comment by marvinfriede** [comment]
I think the question is, whether to change it or leave it to be consistent with `xtb`.

Personally, I think reading the `.CHRG` or `.UHF` from the working directory is totally unintuitive if you can give a path for the coord file. I think this causes more errors than being helpful.

**Comment by hoelzerC** [comment]
Definitely, especially for projects that are build on the implementation this is an avoidable pitfall (like us who opened an issue and mistook it as a wrong implementation for charged systems on our side).

For consistency, it even might be useful to change the `xtb` behavior...

**Comment by awvwgk** [comment]
> For consistency, it even might be useful to change the `xtb` behavior...

Can you open an issue at the `xtb` repository for this?

**Comment by hoelzerC** [comment]
Sure. See [here](https://github.com/grimme-lab/xtb/issues/695)
